#!/usr/bin/python
import sys,re


def parse_myperf(lines):
	lc=0
	count=0
	perf=[]
	for each in lines:
		each=each.rstrip('\n')
		if ( lc == 1):
			lc=0
			perf.append(float(each.split()[2]))
			count+=1
		if ( each[0:2] == "#s"):
			lc=1
	print sum(perf)/count

def parse_filebench(lines):
	perf=[]
	count=0
	for each in lines:
		each=each.rstrip('\n')
		m=re.search(r'IO Summary:.*mb/s',each)
		if(m):
			r=re.search(r'([.0-9]*)mb/s',m.group(0))
			if(r):
				perf.append(float(r.group(1)))
				count+=1
	
	print sum(perf)/count
			
			


def main():
	if(len(sys.argv) < 2):
		print  "Give me file name"
		sys.exit(0)
	lines=[]
	for each in sys.argv[1:]:
		f=open(each)
		lines=lines + f.readlines()
	parse_myperf(lines)
	#parse_filebench(lines)
main()






