#!/usr/bin/python

import sys,re

def parse_cycles(lines):
	cycles=[]
	for each in lines:
		each=each.rstrip('\n')
		m=re.search(r'(Tc:)([0-9]+)',each)
		if(m):
			cycles.append(int(m.group(2)))
	print str(float(sum(cycles))/float(1000000000))[:7]

def main():
	if(len(sys.argv)<2):
		print "Please give a Filename"
		sys.exit(-1)
	lines=[]
	for each in sys.argv[1:]:
		f=open(each)
		if(not f):
			print 0
			return
		lines=lines + f.readlines()
	parse_cycles(lines)
	



main()












#!/bin/bash
#if [[ $1 ]];then
#
#
#
#if [[ -f $1 ]];then
#
#cat $1 | grep Tc | cut -d"," -f6
#
#
#
#fi
#
#else
#echo "GET_CYCLES: Please give a file stats_tmem"
#fi


