#!/usr/bin/python

import sys,re

def parse_cycles(lines):
	cycles=[]
	total_get=[]
	total_put=[]
	for each in lines:
		each=each.rstrip('\n')
		if(len(each)<1):
			continue
		if(each[0]!='P' and each[0]!='C'):
			continue
		m=re.search(r'(Tc:)([0-9]+)',each)
		g=re.search(r'(gt:)([0-9]+)',each)
		p=re.search(r'(pt:)([0-9]+)',each)
		if(m):
			cycles.append(int(m.group(2)))
		if(g):
			total_get.append(0)
			total_get.append(int(g.group(2)))		
		if(p):
			total_get.append(0)
			total_put.append(int(p.group(2)))
		
	#print str(float(sum(cycles))/float(1000000000))[:6]
	ops=float(sum(total_put)+sum(total_get))
	if(ops == 0):
		print 0
	else:
		print str(int(float(sum(cycles))/ops))
		#print str(int(float(sum(cycles))))

def main():
	if(len(sys.argv)<2):
		print "Please give a Filename"
		sys.exit(-1)
	lines=[]
	for each in sys.argv[1:]:
		f=open(each)
		if(not f):
			print 0
			return
		lines=lines + f.readlines()
	parse_cycles(lines)
	



main()












#!/bin/bash
#if [[ $1 ]];then
#
#
#
#if [[ -f $1 ]];then
#
#cat $1 | grep Tc | cut -d"," -f6
#
#
#
#fi
#
#else
#echo "GET_CYCLES: Please give a file stats_tmem"
#fi


