#!/bin/bash

if [[ ! $1 ]];then
	echo "Give stats_G file"
	exit -1
fi

if [[ ! -f `echo $1 | sed 's/tmem/T/'` ]];then
	echo 0
	exit -1

fi

file=`echo $1 | sed 's/tmem/T/'`
up=`cat $file | tr -s " " | tail -n 1 | cut -d" " -f30`
down=`cat $file | tr -s " " | tail -n 1 | cut -d" " -f35`

if [[ !  $down ]];then

	echo 0

else

	echo $up / $down | bc


fi


